all:
	mkdir -p release
	mkdir -p logs
	cp package_docker.json release/package.json
	cd release && npm install
	cat server/Common.coffee server/Room.coffee server/Lobby.coffee server/Game.coffee server/FixedGame.coffee server/TrumpGame.coffee server/PercivalGame.coffee server/Player.coffee server/Database_Postgres.coffee server/Statistics_Minimal.coffee server/Bans.coffee server/Rating.coffee server/Commands.coffee server/Tokens.coffee server/Discussions.coffee server/Main.coffee | coffee --compile --stdio > release/Server.js
	cp -rf client release/client

clean:
	rm -rf release

cleanr:
	rm -rf release/client
	rm -rf release/server